diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=schannel
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
init.defaultbranch=master
core.editor="C:\Users\o0z0o\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
user.name=SmokedSenator
user.email=SCP713@gmail.com
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/SmokedSenator/GitHubStudy
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.GitHubStudy.url=https://github.com/SmokedSenator/GitHubStudy.git
remote.GitHubStudy.fetch=+refs/heads/*:refs/remotes/GitHubStudy/*
remote.PCtoGIT.url=https://github.com/SmokedSenator/PCtoGIT.git
remote.PCtoGIT.fetch=+refs/heads/*:refs/remotes/PCtoGIT/*
